# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

	pod 'CoreNetKit', :path => '../'
	pod 'AlamofireImage', '~> 3.3'
	pod 'SwiftMessages'
	pod 'ReactiveDataDisplayManager', :git=>"https://github.com/LastSprint/ReactiveDataDisplayManager", :commit=>"8c8c9d07f38c3dbe8f5cb56a300521e1f941f5e8"

end
