# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

	pod 'CoreNetKit', :git => 'https://github.com/LastSprint/CoreNetKit.git'
	pod 'SwiftLoader', :git => 'https://github.com/leoru/SwiftLoader.git'

end
