# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BSONExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BSONExample

  pod 'NodeKit', :path => '../'
  pod 'BSON', :git => 'https://github.com/OpenKitten/BSON.git', :branch => 'master/7.0'

end
